[directory]
fish_style_pwd_dir_length = 1

[c]
detect_folders = ["src"]
format = '\[[$symbol($version(-$name))]($style)\]'

[cmake]
disabled = true

[aws]
format = '\[[$symbol($profile)(\($region\))(\[$duration\])]($style)\]'

[azure]
format = '\[[$symbol($subscription)]($style)\]'

[battery]
format = '\[[$symbol$percentage]($style)\]'

[buf]
format = '\[[$symbol]($style)\]'

[bun]
format = '\[[$symbol]($style)\]'

[cmd_duration]
format = '\[[‚è± $duration]($style)\]'
min_time = 5_000

[cobol]
format = '\[[$symbol]($style)\]'

[conda]
format = '\[[$symbol$environment]($style)\]'

[container]
format = '\[[$symbol \[$name\]]($style)\]'

[cpp]
format = '\[[$symbol($version(-$name))]($style)\]'

[crystal]
format = '\[[$symbol]($style)\]'

[daml]
format = '\[[$symbol]($style)\]'

[dart]
format = '\[[$symbol]($style)\]'

[deno]
format = '\[[$symbol]($style)\]'

[direnv]
format = '\[[$symbol$loaded/$allowed]($style)\]'

[docker_context]
format = '\[[$symbol$context]($style)\]'

[dotnet]
format = '\[[$symbol(üéØ $tfm)]($style)\]'

[elixir]
format = '\[[$symbol($version \(OTP $otp_version\))]($style)\]'

[elm]
format = '\[[$symbol]($style)\]'

[erlang]
format = '\[[$symbol]($style)\]'

[fennel]
format = '\[[$symbol]($style)\]'

[fortran]
format = '\[[$symbol]($style)\]'

[fossil_branch]
format = '\[[$symbol$branch]($style)\]'

[fossil_metrics]
format = '\[[+$added]($added_style)\]\[[-$deleted]($deleted_style)\]'

[gcloud]
format = '\[[$symbol$account(@$domain)(\($region\))]($style)\]'

[git_branch]
format = '\[[$symbol$branch]($style)\]'

[git_commit]
format = '\[[\($hash$tag\)]($style)\]'

[git_metrics]
format = '\[[+$added]($added_style)\]\[[-$deleted]($deleted_style)\]'

[git_state]
format = '\[[$state ($progress_current/$progress_total)]($style)\]'

[git_status]
format = '([\[$all_status$ahead_behind\]]($style))'

[gleam]
format = '\[[$symbol]($style)\]'

[golang]
format = '\[[$symbol]($style)\]'

[gradle]
format = '\[[$symbol]($style)\]'

[guix_shell]
format = '\[[$symbol]($style)\]'

[haskell]
format = '\[[$symbol]($style)\]'

[haxe]
format = '\[[$symbol]($style)\]'

[helm]
format = '\[[$symbol]($style)\]'

[hg_branch]
format = '\[[$symbol$branch]($style)\]'

[hostname]
format = '\[[$ssh_symbol($hostname)]($style)\] '

[java]
format = '\[[$symbol]($style)\]'

[jobs]
format = '\[[$symbol$number]($style)\]'

[julia]
format = '\[[$symbol]($style)\]'

[kotlin]
format = '\[[$symbol]($style)\]'

[kubernetes]
format = '\[[$symbol$context( \($namespace\))]($style)\]'

[localip]
format = '\[[$localipv4]($style)\]'

[lua]
format = '\[[$symbol]($style)\]'

[memory_usage]
format = '\[$symbol[$ram( | $swap)]($style)\]'

[meson]
format = '\[[$symbol$project]($style)\]'

[mise]
format = '\[[$symbol$health]($style)\]'

[mojo]
format = '\[[$symbol]($style)\]'

[nats]
format = '\[[$symbol$name]($style)\]'

[netns]
format = '\[[$symbol \[$name\]]($style)\]'

[nim]
format = '\[[$symbol]($style)\]'

[nix_shell]
format = '\[[$symbol$state( \($name\))]($style)\]'

[nodejs]
format = '\[[$symbol]($style)\]'

[ocaml]
format = '\[[$symbol(\($switch_indicator$switch_name\))]($style)\]'

[odin]
format = '\[[$symbol($version )]($style)\]'

[opa]
format = '\[[$symbol]($style)\]'

[openstack]
format = '\[[$symbol$cloud(\($project\))]($style)\]'

[os]
format = '\[[$symbol]($style)\]'

[package]
format = '\[[$symbol$version]($style)\]'

[perl]
format = '\[[$symbol]($style)\]'

[php]
format = '\[[$symbol]($style)\]'

[pijul_channel]
format = '\[[$symbol$channel]($style)\]'

[pixi]
format = '\[[$symbol$version( $environment)]($style)\]'

[pulumi]
format = '\[[$symbol$stack]($style)\]'

[purescript]
format = '\[[$symbol]($style)\]'

[python]
format = '\[[${symbol}${pyenv_prefix}(${version})( \($virtualenv\))]($style)\]'

[quarto]
format = '\[[$symbol]($style)\]'

[raku]
format = '\[[$symbol($version-$vm_version)]($style)\]'

[red]
format = '\[[$symbol]($style)\]'

[rlang]
format = '\[[$symbol]($style)\]'

[ruby]
format = '\[[$symbol]($style)\]'

[rust]
format = '\[[$symbol]($style)\]'

[scala]
format = '\[[$symbol]($style)\]'

[shell]
format = '\[[$indicator]($style)\]'

[singularity]
format = '\[[$symbol\[$env\]]($style)\]'

[solidity]
format = '\[[$symbol]($style)\]'

[spack]
format = '\[[$symbol$environment]($style)\]'

[status]
format = '\[[$symbol$status]($style)\]'

[sudo]
format = '\[[as $symbol]($style)\]'

[swift]
format = '\[[$symbol]($style)\]'

[terraform]
format = '\[[$symbol$workspace]($style)\]'

[time]
format = '\[[$time]($style)\]'

[typst]
format = '\[[$symbol]($style)\]'

[username]
format = '\[[$user]($style)\]'

[vagrant]
format = '\[[$symbol]($style)\]'

[vcsh]
format = '\[vcsh [$symbol$repo]($style)\]'

[vlang]
format = '\[[$symbol]($style)\]'

[xmake]
format = '\[[$symbol]($style)\]'

[zig]
format = '\[[$symbol]($style)\]'
