git:
  autoFetch: false
  autoStageResolvedConflicts: false
  commit:
    signOff: true
  commitPrefix:
    - pattern: "^(\\d+)-.*$"
      replace: '[#$1] '
  pagers:
    - colorArg: always
      pager: delta --dark --paging=never --line-numbers --hyperlinks --hyperlinks-file-link-format="lazygit-edit://{path}:{line}"
gui:
  language: "en"
  border: single
  nerdFontsVersion: 3
os:
  editPreset: "nvim"
keybinding:
  commits:
    moveDownCommit: 'J'
    moveUpCommit: 'K'
