[mgr]
prepend_keymap = [
  { on = "l", run = "plugin smart-enter", desc = "Enter the child directory, or open the file" },
  { on = "p", run = "plugin smart-paste", desc = "Paste into the hovered directory or CWD" },
  { on = "t", run = "plugin smart-tab", desc = "Create a tab and enter the hovered directory" },
  { on = [
    "g",
    "r",
  ], run = 'shell -- ya emit cd "$(git rev-parse --show-toplevel)"', desc = "cd back to the root of the current Git repository" },
  { on = "<C-n>", run = 'shell -- dragon-drop -x -i -T "$0"', desc = "Drag and drop" },
  { on = "<C-m>", run = '''shell --
    paths=$(for p in "$@"; do echo "$p"; done | paste -s -d,)
    thunderbird -compose "attachment='$paths'"
''', desc = "Email selected files" },
]
